require 'aws-sdk'
require 'base64'
require 'digest/sha1'
require 'erb'
require 'json'
require 'logger'
require 'optparse'
require 'singleton'
require 'yaml'

require_relative 'rivet/deep_merge'
require_relative 'rivet/logger'
require_relative 'rivet/utils'
require_relative 'rivet/aws_utils'
require_relative 'rivet/launch_config'
require_relative 'rivet/autoscale'
require_relative 'rivet/bootstrap'
require_relative 'rivet/client'
